### PR TITLE
Update benchmark implementations

### PR DESCRIPTION
**Pull request by weiznich**
* Use the tokio runtime for sqlx/sea-orm as requested here: https://github.com/launchbadge/sqlx/issues/1481#issuecomment-947025316
* Update quaint to a version that uses tokio 1.0 and reenable it in the
  metrics job

cc @billy1624 and @abonander

### CODE REVIEW

**Review by pksunkara — APPROVED** [review]

**Comment by billy1624** [comment]
Thanks!! @weiznich

**Comment by abonander** [comment]
Thanks for incorporating my feedback! It looks like it actually was a pretty good improvement for SQLx across the board. The SQLite driver is still abysmally slow of course but that's something I've actually been working on over the last couple weeks.

**Comment by weiznich** [comment]
@abonander The plots for sqlite are from the results from august, as the current sqlx version segfault while running the benchmarks.:

```
Benchmarking bench_insert/sqlx/1
Benchmarking bench_insert/sqlx/1: Warming up for 3.0000 s
error: process didn't exit successfully: `/home/runner/work/diesel/diesel/diesel_bench/target/release/deps/benchmarks-6af3c2993455c1b2 --bench` (signal: 11, SIGSEGV: invalid memory reference)
```

Do you want me to fill an issue for that in the SQLx issue tracker?

**Comment by abonander** [comment]
Don't worry about it, that's part of what I've been working on.

**Pull request merged**
