### PR TITLE
make ALL_MIGRATIONS public to allow users access to the migrations

### PR DESCRIPTION
**Pull request by eranrund**
Hello!

We'd like to have a way for our programs to terminate if there are pending migrations, and we'd like to have the migrations bundled with our binary so that we don't have to package them separately and can have a single build artifact.

We would like to use code similar to https://github.com/diesel-rs/diesel/blob/master/diesel_migrations/migrations_internals/src/lib.rs#L194-L199 but for that we need access to the embedded migrations. 

Thank you!

### CODE REVIEW

**Comment by weiznich** [comment]
That's basically a duplicate of #2657.

**Comment by eranrund** [comment]
Hey @weiznich 
That PR touches 40 files and I suspect would take some time to get accepted...
It would be great once it lands but I'm hoping the small change in this PR can serve as a bandaid until that happens.

**Comment by eranrund** [comment]
@weiznich I see. Do you have an estimation for when #2657 would land and get released? That could help us plan around it.
Thank you!

**Comment by weiznich** [comment]
As I'm doing this work in my free time I cannot give you any other answer then as soon as it is ready. That's likely sooner if more people start rereviewing or contributing things on our roadmap/milestone.

**Comment by eranrund** [comment]
Totally reasonable. Thank you for your work!

**Pull request closed without merging**
