### PR TITLE
Remove extra semicolon in doctest on_conflict

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Review by henryboisdequin — APPROVED** [review]

**Comment by henryboisdequin** [comment]
@weiznich Am I allowed to merge typo fixes such as this one? 

Also, @pickfire PR looks good.

**Comment by pickfire** [comment]
@henryboisdequin Haha, you need to ask to merge typo fixes? If he give you write access means he trust you enough not to sabotage the repo and take up some of his responsibilities.

**Comment by weiznich** [comment]
@henryboisdequin You shouldn't have the corresponding rights to merge anything in master yet. Those rights belong to the `contributors` group. You can try to merge the PR to see if that's true (if that works I need to rework the access rights for different groups.)

**Comment by henryboisdequin** [comment]
@weiznich Merged, I think you need to edit reviewers rights :)

**Comment by weiznich** [comment]
@henryboisdequin Good to know. I think it should be fixed now. Seems like there is something in GitHub's organization design which overrides the actual team permissions... :disappointed:

**Comment by henryboisdequin** [comment]
@weiznich Yep it's fixed. It would be nice to have the permission to label issues though as that's something reviewers could do and have the time for.

**Comment by weiznich** [comment]
@henryboisdequin I've already changed to permissions so that this is possible. All reviewers should now have [Triage](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization) rights.

**Pull request merged**
