### PR TITLE
Mysql UUID support

### PR DESCRIPTION
**Pull request by Diggsey**
Adds support for querying UUIDs to/from Mysql Binary columns.

### CODE REVIEW

**Comment by weiznich** [comment]
In general your policy for the implementation of `FromSql` /` ToSql` for certain types in diesel is something like the three following questions:

*   Is this a commonly used type. (Yes because there is already support for `Uuid` in diesel.
*   Could we provide a `FromSql` and a `ToSql` implementation for that type. (In this case Yes)
*   Could the conversion go somehow wrong because the sql type or the rust type could hold values that are not representable in the other type. (In this case the conversion from `Vec<u8>` to `Uuid` could go wrong, because not every arbitrary byte sequence is a uuid. Therefore the corresponding constructor returns a `Result`)

Only if we could answer those three questions with:

*   It is a commonly used type
*   We could provide both conversions
*   Nothing could go wrong

we add support for those types.

Because the third question is not answered positively I do not think we want to add support for this conversion (Maybe the members of @diesel-rs/core have a different opinion here?)

**Comment by Diggsey** [comment]
I see. It's unfortunate because in practice, my conversion cannot fail (my columns are `BINARY(16)`).

**Comment by weiznich** [comment]
Unfortunately we cannot enforce this on diesel's side.

**Comment by theduke** [comment]
I know this has been the policy for a while.

Personally I think this badly hurts the usability of Diesel.

I've run into this with `u32/u64` in Postgres, `Uuid` in Mysql and Sqlite, ...

It requires either creating additional structs with the real type, and writing (Try)From/Into impls for easy conversion or coming up with a wrapper type, like shown in https://github.com/diesel-rs/diesel/issues/2098.

Both solutions are incredibly annoying in practice and introduce a lot of boilerplate.

I understand the argument - types should be coherent with the underlying database representation.

But I think the value is limited. Yes, you may get errors due to invalid type mappings. 
But the worst thing that would happen is a conversion error when querying data. And it can be circumvented with a custom wrapper type anyway.

In my opinion, this decision should be left to the developer and  the  strict coherence policy should be loosened in favour of usability.

**Pull request closed without merging**
