### PR TITLE
Fix incorrect error message

### LINKED ISSUE #1977: formatter error
### Versions

- **Rust:** 1.32.0
- **Diesel:** 1.4.1
- **Database:** Postgres 11
- **Operating System** Linux

### Feature Flags

- **diesel:** chrono, postgres, r2d2, uuid

## Problem Description

On connecting to a DB and `embedded_migrations::run(&pool.get()?)?;`-ing, I get the incredibly unhelpful error "formatter error," which seems to be from [deep in std](https://doc.rust-lang.org/src/std/io/mod.rs.html#1146), if the migrations would introduce a constraint violation.

### What are you trying to accomplish?

Apply some migrations to prod that worked in dev

### What is the expected output?

[INFO] Started!

### What is the actual output?

[ERROR] Failed with: formatter error

### Are you seeing any additional errors?

Not from the app/diesel, but from diesel migration run, which shows the error.

### Steps to reproduce

have a DB
ALTER TABLE some check constraints on in a migration
run the migration

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

### PR DESCRIPTION
**Pull request by derekdreery**
Fixes #1977

### CODE REVIEW

**Comment by derekdreery** [comment]
Failure on nightly is because of new lint for mem::uninitialized. Unrelated to PR

**Comment by weiznich** [comment]
Could you rebase this PR on top of #2131 to fix the CI?

**Comment by derekdreery** [comment]
> Could you rebase this PR on top of #2131 to fix the CI?
Done

**Comment by weiznich** [comment]
Closed by #2159

**Pull request closed without merging**
