### PR TITLE
Add like, not_like and concat for PostgreSQL Bytea

### PR DESCRIPTION
**Pull request by Justice4Joffrey**
I saw a couple of issues requestinhg support for this (e.g. #3127).

This is mostly a copy of `TextExpressionMethods`.

Would love to know if there's a more concise way of creating a `Vec<u8>` from a readable literal other than `"S%".as_bytes().to_owned())`.

### CODE REVIEW

**Comment by Mingun** [comment]
I believe, the shortest way is `b"S%".to_vec()`

**Review by weiznich — COMMENTED** [review]
Thanks for opening this PR :+1:

The implementation itself looks good. I would like to see a compile test that demonstrates that code using `like`/`concat`/`not_like` with a binary column only compiles using a postgres connection.

**Comment by Justice4Joffrey** [comment]
In the current implementation, all of these pg-specific expression methods will be available for all `T`'s when the "postgres_backend" feature flag is set. Probably works in practice but is clearly incorrect.

E.g.

``` rust
impl<T> PgTextExpressionMethods for T
where
    T: Expression,
    T::SqlType: TextOrNullableText,
{
}
```

**Comment by weiznich** [comment]
That's what I assumed :wink:.

So the correct way to fix this is to introduce postgres specific variants of the corresponding operators. It should be easy to define them via the `diesel::infix_operation!` macro.

**Comment by Justice4Joffrey** [comment]
Ok I see. I think the take-home here is you should never return a type other than those defined in `pg/helper_types.rs`.

IMO it would be good to make that slightly more obvious. All methods in that file specifically use `helper_types` through the crate-level `dsl` module, which is misleading.

**Review by weiznich — APPROVED** [review]

**Comment by weiznich** [comment]
Thanks for the update :+1:

Yes that requirement could made more clear. I would definitively accept a PR adding corresponding comments. Otherwise I try to remember that and will add a comment there myself as soon as I touch that part of the code again.

**Pull request merged**
