### PR TITLE
Fix Doc Comment Markup

### PR DESCRIPTION
**Pull request by killercup**

### CODE REVIEW

**Comment by killercup** [comment]
cf. <https://www.reddit.com/r/rust/comments/4gbl2j/whats_everyone_working_on_this_week_172016/d2gaxp3?context=5>

**Comment by killercup** [comment]
(Assuming the code still worked was a bit far fetched. I'll look into the failure tonight and will try to fix it)

**Comment by sgrif** [comment]
Nice catch. The fix is pretty easy, just change `Serial` to `Integer`

**Comment by killercup** [comment]
Should be good to go now.

**Comment by sgrif** [comment]
Thanks!

**Pull request merged**
