### PR TITLE
Play with azure-pipeline

### LINKED ISSUE #1838: Switch to Azure for Windows CI
https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/

Appveyor has consistently been painful and slow for us to use, I'd like to look at whether Azure's CI option is an improvement.

### PR DESCRIPTION
**Pull request by weiznich**
This builds everything on all platforms that are supported by azure pipelines.

Someone with admin access to the diesel organisation needs to add a organisation on azure pipelines and configure the setup. (Maybe @sgrif :wink:)

A build can be seen here: https://dev.azure.com/weiznich/diesel-test/_build/results?buildId=187&view=logs. Some of the builds are currently failing but I'm not sure why 😟 

In detail the following to errors occure:

- [x]  All windows builder: There seems to be some issue with the tests for diesel_cli,
- [x] On MacOS the postgres builder is failing at diesel_tests with the following error:
```
---- select::select_for_update_modifiers stdout ----
 thread 'select::select_for_update_modifiers' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"pg_type_typname_nsp_index\"")', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Beside of that I would suggest to move all the ci things to azure because it seems that all those builds are approximately as fast the current travis builds.

Closes #1838 
Closes #1880

### CODE REVIEW

**Comment by h-michael** [comment]
@weiznich 
At #1884, I need sqlite3 that is over v3.24.0, but Ubuntu trusty has 3.8.2.
We have two ways to use sqlite3 v3.24.0.
First, we manually build sqlite3 on Travisci, but that makes build speed slow.
Second, when sqlite3 test runs, we use Ubuntu cosmic(18.10) that has sqlite3 v3.24.0 on Azure pipeline.
Could you try to use Ubuntu cosmic on sqlite3 test?

**Comment by h-michael** [comment]
Sorry, We are available only Ubuntu 16.04 on Azure pipelines.
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml#use-a-microsoft-hosted-agent

**Comment by weiznich** [comment]
@diesel-rs/core I've got everything working beside of an trait overflow error on windows for sqlite. Does anyone has an idea what's happening there?

**Comment by weiznich** [comment]
@diesel-rs/core I've found the problem. (Stupid mistake…)
I propose we merge this PR, disallow uuid 0.7 and then release diesel 1.4

**Pull request merged**
