### PR TITLE
Split sqlite getting started example

### PR DESCRIPTION
**Pull request by ericho**
Split the sqlite example into three parts as the same way that MySQL and PostgreSQL examples does.

Address #776

### CODE REVIEW

**Comment by ericho** [comment]
:open_mouth: I forgot to add that file. 
Now it's there.

**Comment by sgrif** [comment]
Test failures seem related.

**Comment by ericho** [comment]
I make a mistake in the last commit, now the build passed 😄

**Comment by Phrohdoh** [comment]
LGTM (would suggest a squash, personally)

**Comment by killercup** [comment]
Thanks again!

**Pull request merged**
