### PR TITLE
Backport to 1.4.x some PRs marked as "maybe backport"

### PR DESCRIPTION
**Pull request by alfonso-eusebio**
These are the backports to branch 1.4.x of some straightforward PRs that had been marked as "maybe backport".

I've adapted the fix to "properly decrement transaction_depth" so that it doesn't take into account error `DatabaseErrorKind::ReadOnlyTransaction`, which doesn't exist in 1.4.x. But I have included some minor visibility and helper function changes, even though they probably don't make a big different in this branch.

I haven't been able to run the tests locally, but I've compiled the changes against a local binary to make sure there were no compilation issues.

### CODE REVIEW

**Comment by weiznich** [comment]
Thanks for opening this PR :+1:

Test failures are caused by the dotenv update. I think the simplest way to resolve this is to remove the version bump from this backport PR. I do not think it is worth to backport all necessary changes to fix this to 1.4.x as this is solely an internal/dev-dependency for the released crates.

**Comment by alfonso-eusebio** [comment]
Not sure why tests are failing with deprecation errors on unchanged files. Yesterday's PR went through without issues.
Not sure if it's worth looking into getting rid of that Error::description() deprecation problem as part of this PR (?).

**Comment by alfonso-eusebio** [comment]
@weiznich We were writing at the same time. I'm happy to remove the `dotenv` update or try to get rid of the `description()` usage, whatever you guys think is best.

**Comment by weiznich** [comment]
I don't think `Error::description` is the problem here. See for example [this](https://github.com/diesel-rs/diesel/runs/749654567?check_suite_focus=true#step:28:129) test failure. It fails because there is some issue with `error-chain` which is an internal dependency of an really old `dotenv` version, which is used because of the usage of `diesel-infer-schema` in `diesel_tests`. It seems like we just cannot use two different `dotenv` versions here.

**Comment by weiznich** [comment]
I will try to issue a release today or tomorrow

**Pull request merged**
