### PR TITLE
Scope 'options' derive attributes under trait name.

### LINKED ISSUE #558: Rename `options` decorator
Rocket uses `options` as a decorator to declare an HTTP `options` route. Diesel uses it to declare options on schemas. This causes a collision when the two libraries are used together, resulting in a compilation error.

It seems that the `options` decorator isn't used frequently by end-users in Diesel, while `options` in Rocket is one of the core decorators. Would you consider renaming `options` to `schema_options` or `table_options`, or something else, so that the two can coexist before macro renaming is allowed?

### PR DESCRIPTION
**Pull request by SergioBenitez**
Resolves #558.

### CODE REVIEW

**Comment by sgrif** [comment]
I think we could change a bit less code if we use a single name like `diesel_codegen_options` instead.

**Comment by SergioBenitez** [comment]
I found it confusing that different "options" parameters had the same name. I think having different names makes the code easier to read and grep later.

**Comment by sgrif** [comment]
I honestly don't have that strong an opinion. Can you changes which are formatting-only? I will merge after that

**Comment by SergioBenitez** [comment]
Sure. That's rustfmt, by the way.

**Comment by sgrif** [comment]
It's not that I disagree with the changes, just that we prefer to avoid git-churn as much as possible.

**Comment by SergioBenitez** [comment]
Failures are unrelated to these changes.

**Comment by killercup** [comment]
Travis failures are from proc_macro becoming stable and deny(warnings). Will make a PR to remove the feature attrs later.

**Comment by killercup** [comment]
@SergioBenitez can you rebase this on master to see if the tests pass? I'll merge it after that.

**Comment by SergioBenitez** [comment]
Done.

**Comment by killercup** [comment]
Sweet! Merging!

**Pull request merged**
