### PR TITLE
Faillible Queryable - Non-generic Queryable version experiment

### PR DESCRIPTION
**Pull request by Ten0**
One approach to fixing #2523

### CODE REVIEW

**Comment by weiznich** [comment]
Just to drop a note here: I'm currently busy with other work related stuff, so I will likely not be able to look at this for the next week or so.

**Comment by Ten0** [comment]
So the test fails there seems to highlight a compatibility break with type inference where the compiler cannot infer "oh there's a single type I know for deserializing BigInt, that's `i64`, let me just use that" anymore, though I'm not sure why it has this impact.

If going for this approach, `readme`s and diesel_cli would still have to be updated.

**Comment by weiznich** [comment]
Another important change here is that we cannot anymore write different impls depending on the type returned by some query or the backend. Doing that is basically required to port `diesel_cli`. As consequence I would like to see how that could be solved before looking any further into this.

**Comment by Ten0** [comment]
> Another important change here is that we cannot anymore write different impls depending on the type returned by some query or the backend. Doing that is basically required to port `diesel_cli`. As consequence I would like to see how that could be solved before looking any further into this.

From https://github.com/diesel-rs/diesel/issues/2523#issuecomment-703781510:
> it would probably always be implemented without an additional layer of genericity, so it could probably use `FromSqlRow` instead of `Queryable`, as the _conflicting impl_ error wouldn't trigger.

As it turns out, we're actually using a bit of genericity here:
https://github.com/diesel-rs/diesel/blob/a312528c7cce6b25ae6f1f5987f784b635b18ed6/diesel_cli/src/infer_schema_internals/data_structures.rs#L78-L82

but for some reason it still works. (Maybe thanks to the local `UsesInformationSchema` trait.)

**Comment by Ten0** [comment]
One more issue: rust error messages suggest less correct approaches to fixing `FromSqlRow<ST, DB> is not implemented for T`:
https://github.com/diesel-rs/diesel/pull/2559/checks?check_run_id=1617158750#step:6:258

**Comment by weiznich** [comment]
Closed as I would like to go with #2599

**Pull request closed without merging**
