### PR TITLE
Add `Bool` type to MultiConnection

### PR DESCRIPTION
**Pull request by BlackDex**
During trying to implement MultiConnection i found that the `Bool` type was missing.

This PR adds this type.

### CODE REVIEW

**Comment by weiznich** [comment]
I think just adding this impl would be a breaking change :(

Existing users of `#[derive(MultiConnection)]` could have already manually implemented that these traits. On the other hand "breaking" changes are allowed for bug fixes and we could argue that this is a bug fix. 
(I wouldn't expect any breakage here as otherwise we would have seen reports about the missing impl earlier)

**Comment by BlackDex** [comment]
I would also say this is a bug fix, since this is a missing default type. It's not that this is a whole new type not previously existing on the separate backends.

**Comment by weiznich** [comment]
cc @diesel-rs/core on whether or no we want to consider that as bug fix.

**Comment by sgrif** [comment]
This seems backwards compatible afaict so treating it as a bug fix seems fine

**Comment by Ten0** [comment]
IMO if somebody was competent enough to realize that impl was missing and implemented it manually without bothering to open an issue, breaking change is fair enough ^^

**Review by Ten0 — APPROVED** [review]

**Comment by weiznich** [comment]
Thanks for the swift responses. Seems like we are all on line in calling this a bug fix :+1:

@pksunkara Your input is appreciated here as well :heart:

**Pull request merged**
