### PR TITLE
Upgrade dotenv

### PR DESCRIPTION
**Pull request by mehcode**
Not sure the best way to handle the switch to Failure. `dotenv::Error` no longer implements `std::error::Error` so its awkward to use it with `Box<Error>`.

### CODE REVIEW

**Comment by xianghx** [comment]
https://github.com/purpliminal/rust-dotenv
page not found.

what happen?

**Comment by mehcode** [comment]
Not sure. Hope she's okay.

Perhaps @sgrif knows? 

It seems @sgrif has write access on crates.io in any case.

**Comment by weiznich** [comment]
Seems like the build of [diesel_tests is broken](https://travis-ci.org/diesel-rs/diesel/jobs/446467644#L1685) after this.
Also this needs a rustfmt run (rustfmt from rust 1.26.1)

**Comment by mehcode** [comment]
Closing as I don't have the time to drive this forward. I'll wait until a new dotenv rolls out from @sgrif or someone else.

**Pull request closed without merging**
