### PR TITLE
Allow for "bool" type from django with tests

### PR DESCRIPTION
**Pull request by social-anthrax**
Taken from PR #3239:
> Hey all.
> 
> Encountered this issue while attempting to modernize a Django app by running `diesel print-schema` on an already created SQLite3 db, which returned `Unsupported type: bool`.
> 
> Django appears to have [used `"bool"` for their types](https://github.com/django/django/blob/24effbceb871e71d3bc320b91252f743714722df/django/db/backends/sqlite3/base.py#L32) instead of `"boolean"`.

This PR is continued from #3239, with two additions

- `type_name.contains("bool")` has been changed to `type_name.starts_with("bool")` to match fewer cases. 
- test has been implemented in diesel_cli/tests/print_schema.rs

### CODE REVIEW

**Comment by czotomo** [comment]
I see one problem, and that problem is sqlite's type system. This is perfectly legal:
`sqlite> create table foo (x booldozer, y boolbool);
sqlite> insert into foo values (1, 2);
sqlite> select * from foo;
1|2`

**Comment by social-anthrax** [comment]
I see your point. Would it be better to strictly match bool and boolean?

**Comment by czotomo** [comment]
> I see your point. Would it be better to strictly match bool and boolean?

I am not sure. Strict matching is safer, but it's also ... strict. 
Either do that, or maybe log a "you have such and such type and it's going to be treated as boolean" message?

**Comment by social-anthrax** [comment]
I feel that at the moment only bool and boolean have been encountered, so it's easy enough to do a strict match. Maybe in the future if more issues like this arise it will be worth matching anything starting with bool and throwing a warning

**Review by weiznich — APPROVED** [review]
Thanks for including the tests :+1:

**Comment by weiznich** [comment]
I believe it's fine to explicitly match these two cases for now. In the medium term I would suggest that we allow to configure that mapping via `diesel.toml`. That means that we only support the basic "real" sqlite types, and everything else is configured there via a list of regular expressions and replacements or something like that. That would allow to customize these mappings much easier based on specific usecases. I would be happy to mentor work in that direction.

**Pull request merged**
