### PR TITLE
Implement `EqAll` for all supported tuple sizes

### PR DESCRIPTION
**Pull request by sgrif**
I'm not sure why we didn't always go with something like this, it would
have worked with any version of Rust (we aren't using type macros here).
I think I just wasn't well versed enough with Rust's type/macro system
at that point in time.

Anyway, this just implements every version of `EqAll` in terms of the
implementation for one smaller sized tuple. We handle the single element
tuple case separately to terminate the recursion.

Close #1699.

### CODE REVIEW

**Comment by ivanovaleksey** [comment]
Thanks @sgrif!
Shouldn't we update documentation about limits on composite PK size?
I mean in `diesel/src/macros/mod.rs`.
Are any updates required to `print-schema` tool? Right now it checks PKs count explicitly.

**Comment by sgrif** [comment]
Probably yes. This was just a quick PR, feel free to take over and finish those things

**Comment by ivanovaleksey** [comment]
@sgrif do you mean I could push updates for you PR? Not sure if I am allowed to do this. Isn't it allowed only for maintainers?

And what do we have now? There is no special limit on PK size, so 
- in [`diesel/src/macros/mod.rs`](https://github.com/diesel-rs/diesel/blob/master/diesel/src/macros/mod.rs#L122) we could just place 
```
/// Tables with no primary key are not supported.
```
- in [`diesel_infer_schema/infer_schema_internals/src/inference.rs`](https://github.com/diesel-rs/diesel/blob/master/diesel_infer_schema/infer_schema_internals/src/inference.rs#L142) we could remove `else if` arm altogether

right?

**Comment by ivanovaleksey** [comment]
@sgrif I run `print-schema` (with PK size commented) and `joinable!` was removed too (like in my original PR).
Does it mean that something else should be patched?

```diff
diff --git a/migrations/2018-04-16-123630_create_abac_policy/up.sql b/migrations/2018-04-16-123630_create_abac_policy/up.sql
index d38cf17..6014480 100644
--- a/migrations/2018-04-16-123630_create_abac_policy/up.sql
+++ b/migrations/2018-04-16-123630_create_abac_policy/up.sql
@@ -1,13 +1,21 @@
 create table abac_policy (
-  id uuid default uuid_generate_v4(),
   namespace_id uuid not null,
+  subject_namespace_id uuid not null,
+  subject_key text not null,
   subject_value text not null,
+  object_namespace_id uuid not null,
+  object_key text not null,
   object_value text not null,
+  action_namespace_id uuid not null,
+  action_key text not null,
   action_value text not null,
   issued_at timestamp not null default now(),
   not_before timestamp,
   expired_at timestamp,
 
   foreign key (namespace_id) references namespace (id) on delete cascade,
-  primary key (id)
+  foreign key (subject_namespace_id) references namespace (id) on delete cascade,
+  foreign key (object_namespace_id) references namespace (id) on delete cascade,
+  foreign key (action_namespace_id) references namespace (id) on delete cascade,
+  primary key (namespace_id, subject_namespace_id, subject_key, subject_value, object_namespace_id, object_key, object_value, action_namespace_id, action_key, action_value)
 );

diff --git src/schema.rs src/schema.rs
index 8707262..2ff1bc1 100644
--- src/schema.rs
+++ src/schema.rs
@@ -17,11 +17,16 @@ table! {
 }

 table! {
-    abac_policy (id) {
-        id -> Uuid,
+    abac_policy (namespace_id, subject_namespace_id, subject_key, subject_value, object_namespace_id, object_key, object_value, action_namespace_id, action_key, action_value) {
         namespace_id -> Uuid,
+        subject_namespace_id -> Uuid,
+        subject_key -> Text,
         subject_value -> Text,
+        object_namespace_id -> Uuid,
+        object_key -> Text,
         object_value -> Text,
+        action_namespace_id -> Uuid,
+        action_key -> Text,
         action_value -> Text,
         issued_at -> Timestamp,
         not_before -> Nullable<Timestamp>,
@@ -78,7 +83,6 @@ table! {

 joinable!(abac_action_attr -> namespace (namespace_id));
 joinable!(abac_object_attr -> namespace (namespace_id));
-joinable!(abac_policy -> namespace (namespace_id));
 joinable!(abac_subject_attr -> namespace (namespace_id));
 joinable!(identity -> namespace (provider));
 joinable!(namespace -> account (account_id));
```

**Comment by sgrif** [comment]
@ivanovaleksey Yes, feel free to clone this branch, make your changes, and then open a new PR

**Comment by sgrif** [comment]
Or just copy the code from here

**Comment by sgrif** [comment]
@ivanovaleksey Were you still interested in working on this?

**Comment by ivanovaleksey** [comment]
@sgrif sorry for being silent all these days. Yes, I am still interested in this.
I plan to follow this way
> feel free to clone this branch, make your changes, and then open a new PR

and add changes proposed in [this comment](https://github.com/diesel-rs/diesel/pull/1702#issuecomment-390197386).

By the way, could you please take a look at [this comment](https://github.com/diesel-rs/diesel/pull/1702#issuecomment-390203581).
It looks to me like a problem.

**Comment by ivanovaleksey** [comment]
@sgrif I have cherry-picked you commit and decided to continue a work on my initial PR https://github.com/diesel-rs/diesel/pull/1699.
I guess this PR can be closed.

**Pull request closed without merging**
