### PR TITLE
Use windows 2019 instead of windows latest

### PR DESCRIPTION
**Pull request by Sytten**
Lets see if it helps

### CODE REVIEW

**Comment by weiznich** [comment]
https://github.com/diesel-rs/diesel/commit/d9d46ad11b2d37c4ee43b123a77241c2a06a584d might be relevant for fixing the sqlite build failure.

**Comment by Sytten** [comment]
It seems like the issue is the lib command

**Comment by weiznich** [comment]
Yes, the linked commit fixed that for the windows 2022 image. I think we just need to revert that one to make it work with the older image again.

**Comment by Sytten** [comment]
Reverting the fix didn't seem to help

**Comment by Sytten** [comment]
@weiznich seems to work!

**Comment by weiznich** [comment]
Thanks ❤️

**Pull request merged**
