### PR TITLE
Updated ipnetwork to 0.20

### PR DESCRIPTION
**Pull request by Razican**
This PR updates the ipnetwork dependency to also allow ipnetwork 0.20.

### CODE REVIEW

**Comment by Razican** [comment]
It seems that `clap` now requires 1.56.1, instead of 1.56.0, and this breaks the build.

**Review by weiznich — APPROVED** [review]
This looks fine to me. Before merging a changelog entry should be added.

**Comment by Razican** [comment]
> This looks fine to me. Before merging a changelog entry should be added.

I'm adding that change. Should I update the minimum supported Rust version to 1.56.1 too?

**Comment by weiznich** [comment]
> Should I update the minimum supported Rust version to 1.56.1 too?

I've already pushed that fix.

**Pull request merged**
