### PR TITLE
Upgrade Clippy to 0.121

### PR DESCRIPTION
**Pull request by DorianListens**
Previous versions of clippy no longer compile with nightly rust after 2017-03-17.
See rust-clippy#1633

### CODE REVIEW

**Comment by killercup** [comment]
Thanks! You'll also need to bump the nightly version in the `.travis.yml` file.

**Comment by DorianListens** [comment]
Oh, of course! Thanks!

**Comment by DorianListens** [comment]
My change to the `.travis.yml` file didn't seem to actually get travis to upgrade it's nightly rust version. Is there something else I need to do here?

**Comment by killercup** [comment]
That is weird! Can you push a new comment (maybe just edit/add a comment or something like that) to trigger travis again and see if it's just a caching problem?

**Comment by DorianListens** [comment]
Yep, that seemed to do the trick!

**Comment by killercup** [comment]
Cool, thank's for that. Can you amend without that comment now? 😄 I'll merge it immediately.

**Comment by DorianListens** [comment]
Whoops!

**Comment by killercup** [comment]
Thanks again!

**Pull request merged**
