### PR TITLE
Align getting started example imports with repo

### LINKED ISSUE #1758: src/lib.rs from getting started guide is different from github source.
On the [getting started guide](http://diesel.rs/guides/getting-started/)
the use section of src/lib.rs contains
```
use diesel::prelude::*;
use diesel::pg::PgConnection;
use dotenv::dotenv;
use std::env;
```

but in the [github source](https://github.com/diesel-rs/diesel/blob/v1.3.0/examples/postgres/getting_started_step_1/src/lib.rs#L8) it contains 

```
use diesel::prelude::*;
use dotenv::dotenv;
use std::env;

```

### PR DESCRIPTION
**Pull request by tyre**
While the prelude imports `PgConnection`, it's a confusing mis-match for beginners.

Fixes #1758

### CODE REVIEW

**Comment by weiznich** [comment]
You need to run rustfmt on the changed file to fix the ci otherwise this seems fine. :+1:

**Comment by tyre** [comment]
@weiznich Fixed!

**Comment by weiznich** [comment]
Looks fine, but CI continues to fail because of a unrelated issue. (We have already a fix for this but it is currently in review).

**Comment by JohnTitor** [comment]
@weiznich This looks good to me but the ci is too old and red. Could we make it green? (Still needs rebasing?)

**Comment by TaKO8Ki** [comment]
This pull request was rebased onto master, so I closed it.

**Pull request closed without merging**
