### PR TITLE
Add support for `INSERT OR REPLACE` on SQLite

### PR DESCRIPTION
**Pull request by sgrif**
First piece of #196. SQLite has extremely simple semantics here. `INSERT
OR REPLACE` will literally take what the new row would have been had the
insert succeeded, and will replace the existing row with it. For this to
be most useful, we'll probably want to make it easier to use non-literal
expressions in insert at some point in the future. We'll need to see
what other usage looks like.

This also lays the groundwork for supporting the other modifiers on
SQLite. I had originally planned on doing an API that looks more like
what PG will look like. However, since the semantics are so different,
we'll probably want to keep the APIs from stepping on each others toes.

Another alternative I had leaned towards was `insert.or(replace)`.
However, as I started thinking about the compile fail tests that'd be
required there, and saw the implementation, I shied away from it. Since
there's a fixed set of 4 modifiers that we will support, I think one
function each is fine.

### CODE REVIEW

**Comment by sgrif** [comment]
Review? @diesel-rs/core 

/cc @llogiq

**Comment by llogiq** [comment]
@sgrif Thanks for the ping and the fast implementation. I'm very impressed with what I see so far. In fact I'm so impressed, I may blog about it.

**Comment by sgrif** [comment]
@llogiq :heart: !!! Let me know if there's anything else you're missing.

**Comment by mfpiccolo** [comment]
LGTM.

**Comment by llogiq** [comment]
Cool! :+1:

**Pull request merged**
