### PR TITLE
Specify type of diesel::row::NamedRow::get in QueryableByName macro.

### LINKED ISSUE #4131: Ambiguous traits in QueryableByName derivation when two fields have same concrete type but different SQL types
### Versions

- **Rust:** 1.80.0
- **Diesel:** 2.2.2
- **Database:** PostgreSQL
- **Operating System: ** MacOS

### Feature Flags

- **diesel:** `postgres`

### What are you trying to accomplish?

Attempting to use `QueryableByName` + `sql_query`. In this case, two fields have the same type in the struct, but different SQL types.

Example:
```rust
#[derive(QueryableByName)]
#[diesel(check_for_backend(Pg))]
struct StructWithTextAndCitext {
    #[diesel(sql_type = sql_types::Text)]
    name: String,
    #[diesel(sql_type = sql_types::Citext)]
    email: String,
}
```

Alternative example (this also requires the `serde_json` feature of diesel):
```rust
#[derive(QueryableByName)]
#[diesel(check_for_backend(Pg))]
struct StructWithJsonAndJsonb {
    #[diesel(sql_type = sql_types::Json)]
    v1: serde_json::Value,
    #[diesel(sql_type = sql_types::Jsonb)]
    v2: serde_json::Value,
}
```

### What is the expected output?

The code compiles, and creates a useful `QueryableByName` trait implementation.

### What is the actual output?

In the first case above, the error is:

```
error[E0283]: type annotations needed
   --> src/main.rs:11:10
    |
11  | #[derive(QueryableByName)]
    |          ^^^^^^^^^^^^^^^ cannot infer type
    |
    = note: cannot satisfy `String: FromSql<_, __DB>`
    = help: the following types implement trait `FromSql<A, DB>`:
              <String as FromSql<Citext, Pg>>
              <String as FromSql<ST, DB>>
note: required by a bound in `diesel::row::NamedRow::get`
   --> /xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/diesel-2.2.2/src/row.rs:133:12
    |
131 |     fn get<ST, T>(&self, column_name: &str) -> deserialize::Result<T>
    |        --- required by a bound in this associated function
132 |     where
133 |         T: FromSql<ST, DB>;
    |            ^^^^^^^^^^^^^^^ required by this bound in `NamedRow::get`
    = note: this error originates in the derive macro `QueryableByName` (in Nightly builds, run with -Z macro-backtrace for more info)
```

In the second case, the error is:

```
error[E0283]: type annotations needed
   --> src/main.rs:11:10
    |
11  | #[derive(QueryableByName)]
    |          ^^^^^^^^^^^^^^^ cannot infer type
    |
    = note: cannot satisfy `Value: FromSql<_, __DB>`
    = help: the following types implement trait `FromSql<A, DB>`:
              <Value as FromSql<Json, Pg>>
              <Value as FromSql<Jsonb, Pg>>
note: required by a bound in `diesel::row::NamedRow::get`
   --> /xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/diesel-2.2.2/src/row.rs:133:12
    |
131 |     fn get<ST, T>(&self, column_name: &str) -> deserialize::Result<T>
    |        --- required by a bound in this associated function
132 |     where
133 |         T: FromSql<ST, DB>;
    |            ^^^^^^^^^^^^^^^ required by this bound in `NamedRow::get`
    = note: this error originates in the derive macro `QueryableByName` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Steps to reproduce

Write the code above, with `diesel` dependency, and features `postgres` (and `serde_json` in the second case). If added to `src/main.rs`, you should see the above compile errors. 

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

### PR DESCRIPTION
**Pull request by fiadliel**
Resolves #4131 

`diesel::row::NamedRow::get` has the signature
```
fn get<ST, T>(&self, column_name: &str) -> Result<T>
where
    T: FromSql<ST, DB>
```

This can be inferred from the resulting value, if there is only one `ST` type in scope for `FromSql<ST, DB>`.

But if multiple types are in scope, e.g. 
```
impl<__DB: diesel::backend::Backend> QueryableByName<__DB>
for StructWithTextAndCitext
where
    String: diesel::deserialize::FromSql<sql_types::Text, __DB>,
    String: diesel::deserialize::FromSql<sql_types::Citext, __DB>,
{
```

then `ST` cannot be inferred.

### CODE REVIEW

**Comment by fiadliel** [comment]
This looks like an issue, I'll look into it a bit more:
```
select_expression = (users::id + 45),
                    ^^^^^^^^^^^^^^^^ expected `id`, found `Add<id, Bound<Integer, i32>>
```

**Comment by weiznich** [comment]
That's related to the rust release yesterday. See https://github.com/diesel-rs/diesel/pull/4130/files for the fixes for CI.

**Comment by fiadliel** [comment]
@weiznich Added two tests.

They use `citext`, which is Postgres-only, but it's the only example of the issue that doesn't need any extra features compiled.
Also, let me know if you have a better idea for how to install the citext extension. It appears that `CREATE EXTENSION IF NOT EXISTS` is racy when run on the different connections at around the same time, so I'm doing it in the tests rather than at connection setup.

**Review by weiznich — APPROVED** [review]
Thanks :+1:

I changed the test case to not depend on citext anymore. This solves the parallel initialization issue. I verified that it still produces the issue without fix.

**Comment by fiadliel** [comment]
Thanks!

**Pull request merged**
