### PR TITLE
Fix #384 (Invalid query on empty insert/select in)

### LINKED ISSUE #384: Insert is crashing while trying to insert an empty vector
While trying to insert a dynamically generated vector of values diesel is crashing. It turns out the vector was empty in this special case. 
I expect insert to handle the case of an empty vector and simply do nothing.

Backtrace:

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/user/.cargo/git/checkouts/diesel-6e3331fb3b9331ec/master/diesel/src/persistable.rs:75
stack backtrace:
   1:     0x55be81a907af - std::sys::backtrace::tracing::imp::write::h6528da8103c51ab9
   2:     0x55be81a940cb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hbe741a5cc3c49508
   3:     0x55be81a93d4f - std::panicking::default_hook::he0146e6a74621cb4
   4:     0x55be81a84eae - std::panicking::rust_panic_with_hook::h983af77c1a2e581b
   5:     0x55be81a94311 - std::panicking::begin_panic::he426e15a3766089a
   6:     0x55be81a8597a - std::panicking::begin_panic_fmt::hdddb415186c241e7
   7:     0x55be81a942ae - rust_begin_unwind
   8:     0x55be81aca0bf - core::panicking::panic_fmt::hf4e16cb7f0d41a25
   9:     0x55be81aca232 - core::panicking::panic_bounds_check::h14f942e6ac026712
  10:     0x55be816c5a4b - _<diesel..persistable..BatchInsertValues<'a, T, U, DB> as diesel..persistable..InsertValues<DB>>::column_names::h03daedf58da373b5
                        at /home/user/.cargo/git/checkouts/diesel-6e3331fb3b9331ec/master/diesel/src/persistable.rs:75
  11:     0x55be816c56b9 - _<diesel..query_builder..insert_statement..InsertStatement<T, U, Op> as diesel..query_builder..QueryFragment<DB>>::to_sql::hcb041fa647432d9e
                        at /home/user/.cargo/git/checkouts/diesel-6e3331fb3b9331ec/master/diesel/src/query_builder/insert_statement.rs:57
  12:     0x55be816c1ca5 - diesel::pg::connection::PgConnection::prepare_query::h6125a754ac0ff8c3
                        at /home/user/.cargo/git/checkouts/diesel-6e3331fb3b9331ec/master/diesel/src/pg/connection/mod.rs:149
  13:     0x55be816c1437 - _<diesel..pg..connection..PgConnection as diesel..connection..Connection>::execute_returning_count::h1ec38088d0b52120
                        at /home/user/.cargo/git/checkouts/diesel-6e3331fb3b9331ec/master/diesel/src/pg/connection/mod.rs:80
  14:     0x55be816c13e3 - diesel::query_dsl::load_dsl::ExecuteDsl::execute::h9f4cf5b34b6be13f
                        at /home/user/.cargo/git/checkouts/diesel-6e3331fb3b9331ec/master/diesel/src/query_dsl/load_dsl.rs:69
...
```

### PR DESCRIPTION
**Pull request by weiznich**
Check if a queryresult would be empty
- do not execute such queries, because they are invalid, instead simply
  return nothing

Fix #384

### CODE REVIEW

**Comment by killercup** [comment]
Oh, nice! Do we handle empty arrays anywhere else? Can you add a test for this?

**Comment by weiznich** [comment]
I realized that this fixes the issue only partially. I will try to add tests and provide a better fix for this in the next few days.

**Comment by weiznich** [comment]
I've updated the implementation to handle more cases. Also I realized that this could also fix #384.
I'm not sure if I've implemented `is_empty` in all places where it is needed.

**Comment by killercup** [comment]
@weiznich I just remembered that I tried fixing that and @sgrif and I discussed an implementation in <https://github.com/diesel-rs/diesel/pull/385>, which resulted in our idea to refactor the error handling instead of introducing an `is_empty` method for this one case.

**Comment by weiznich** [comment]
I think using a custom error for this would be problematic, because I think a user expect such queries to succeed. Furthermore with using an `is_empty` method we can save a call into the database, because we can reason about situations where the query would be illegal.

**Comment by weiznich** [comment]
Any news on this? It's annoying and error prone to check in every place where you use eq_any or insert for an empty input.

**Comment by sgrif** [comment]
@weiznich As mentioned, I'd prefer an implementation that looked something like https://github.com/diesel-rs/diesel/pull/385#issuecomment-236690138. The query would still succeed from the user's point of view, as we'd handle the error in the connection itself. See the discussion on the linked thread.

**Comment by sgrif** [comment]
Going to tackle this tomorrow

**Comment by weiznich** [comment]
@sgrif I've opened a pullrequst to @killercup repo which rebases and improves his pull request.

**Pull request closed without merging**
