### PR TITLE
Ensure deterministic ordering of inferred SQLite tables

### PR DESCRIPTION
**Pull request by Mrmaxmeier**
The output generated by `diesel print-schema` is not stable across database environments.
I guess it's sensible to sort the tables alphabetically to be able to diff schemas.

### CODE REVIEW

**Comment by sgrif** [comment]
Can we do the sorting in the actual queries that we execute instead?

**Comment by Mrmaxmeier** [comment]
Sure, that makes sense and is consistent with [the code that does this ordering on Postgres/MySQL already](https://github.com/diesel-rs/diesel/commit/9ed311f97b2b6d5de0808c57aaec735c56d058e5).
I've added the same behavior to the SQLite variant. Should I keep the tests and move them to `diesel_tests`?

**Comment by killercup** [comment]
Yeah, that's way better.

@Mrmaxmeier, I'd keep the cli test and add a small unit test to `diesel_infer_schema/src/sqlite.rs` as well. (Do the others have tests for that? If not, maybe you can add them for PG and MySQL too).

**Comment by Mrmaxmeier** [comment]
I've added unit tests for SQLite, PG and MySQL and Travis seems happy with them.

**Comment by killercup** [comment]
Thanks, great work!

**Pull request merged**
