### PR TITLE
Remove time dependency from chrono

### PR DESCRIPTION
**Pull request by AldaronLau**
I know this is changed in the master branch, but it would be nice to have on 1.4.x as well, considering that 2.0.0 isn't out yet.

### CODE REVIEW

**Comment by weiznich** [comment]
Thanks for submitting this PR. As of today we do not plan to issue another 1.4.x release. That's reserved for finding a critical bug that needs to be fixed. I consider this feature to be a nice to have change so I would include it in an already planed release, but won't cut a new release for it. As of this I will leave this PR open till either 2.0 is released or we cut another 1.4.x release.
That written: The CI failures look legit. A requirement for maybe including this into a release would be a passing CI.

**Comment by AldaronLau** [comment]
@weiznich Updated PR to add required `chrono/clock` feature, but CI is still failing on some of the checks for odd reasons.

Also, I looked but couldn't find - is there a roadmap or timeline for the 2.0.0 release?

**Comment by weiznich** [comment]
> Also, I looked but couldn't find - is there a roadmap or timeline for the 2.0.0 release?

We do not have a public roadmap or timeline for the next release, but I would say it shouldn't be to far away (at least a rc release). Open issues/PR's that are relevant are: https://github.com/diesel-rs/diesel/pull/2996, https://github.com/diesel-rs/diesel/pull/3021 and some sort of fix for https://github.com/diesel-rs/diesel/issues/3016. Any help there would be welcome and would enable an earlier release.

**Comment by weiznich** [comment]
About the CI errors: The sqlite and mysql cases would likely require a backport of https://github.com/diesel-rs/diesel/pull/3052. The compile tests ci run points out a real issue. The minimal supported chrono version does not have the relevant feature. This likely indicates we would need to bump that minimal version, which is something that is not possible as patch release. (Strictly speaking that would require a major version bump)

**Comment by weiznich** [comment]
Closed as 2.0.0 is finally released. It does contain this fix.

**Pull request closed without merging**
