### PR TITLE
WIP/Prototype  - Remove From<Error> bound from Connection::transaction

### PR DESCRIPTION
**Pull request by jacob-pro**
A possible solution to https://github.com/diesel-rs/diesel/issues/2342

### CODE REVIEW

**Comment by Ten0** [comment]
It looks like this would definitely not be something we'd use, so I'm wondering to what extent this is worth the added complexity in the codebase and for users to generally consider. 

Our use case is using an `anyhow`-like error type to generate backtraces and return internal errors such as the ones encountered when using Diesel, which are then reported to an error monitoring system before being converted into errors destined to the end user. (so using this would decrease the quality of the backtrace, and have our functions juggle between unnecessary conversions) 

Can you:
- Provide an example of what your use-case is and how this would increase its ergonomics
- Show how it is not solved by defining this same enum you add in this PR in one of your own crates and using it as the error type for the already existing transaction function (specifically, it looks like it would even enable you to have an `From<TransactionError> for SomeOtherExternalError` impl which you couldn't have here because you wouldn't own any of the types nor the trait)

(NB: Possibly the issue is a better place for this than the PR?)

**Comment by weiznich** [comment]
@jacob-pro If you expect this to  discussed you need to provide answers to the question above. Otherwise I likely will close this PR next week due to inactivity.

**Comment by jacob-pro** [comment]
1. So my usecase is when building an API (using actix), I want to return a standardised `http_api_problem` error (which is defined in an external crate) from each of the route handlers.

3. Defining the enum in my own crate does work, its just that then I have this boilerplate code that I either: (a) have to copy and paste everywhere, or (b) create a very tiny library just containing the code I have included in this PR, it would in my opinion be preferable to have this as part of the diesel API itself...

4. So this is a valid concern, but it the usecase I described the same problem exists even without transactions, i.e. say I want to perform just a simple database query, I already have to have my own function trait for converting the disel error to the `http_api_problem` error in the firstplace since I can't implement From. 

Example: https://github.com/jacob-pro/calpol/blob/525fba9cce33cdb07460deaa34e748ff35d874a3/src/api/v1/users.rs#L171-L176

**Comment by Ten0** [comment]
https://github.com/diesel-rs/diesel/issues/2342#issuecomment-1086631629

**Comment by Ten0** [comment]
https://github.com/diesel-rs/diesel/issues/2342#issuecomment-1086649534

**Pull request closed without merging**
