### PR TITLE
Rustup to 2018-03-19

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by Eijebong** [comment]
Let's see if this actually fixes the nightly tests

**Comment by weiznich** [comment]
Seems like we [crashing](https://travis-ci.org/diesel-rs/diesel/jobs/355827115#L499) rustc

**Comment by Eijebong** [comment]
Yep... I thought this was clippy but nope... Going to report the bug

**Comment by Eijebong** [comment]
https://github.com/rust-lang/rust/issues/49207

**Comment by sgrif** [comment]
I'm so glad that panics in custom derives don't report as ICEs anymore

**Comment by weiznich** [comment]
CI [fails](https://travis-ci.org/diesel-rs/diesel/jobs/358836772#L2301) because of #1556, some new clippy warnings and some changed compile test output.

**Comment by Eijebong** [comment]
Nice, I guess I'll close this in favor of #1600 then since it already fixes clippy tests

**Pull request closed without merging**
