### PR TITLE
Backport fixes to 2.0.x branch

### PR DESCRIPTION
**Pull request by weiznich**
This essentially prepares the final 2.0.0 release by:
* Backporting all relevant fixes
* Bumping the version numbers
* Adding a `Cargo.lock` file as this hopefully allows us to checkout this branch at any later point in time and it will continue to build. This should not affect the release to crates.io in any way.

### CODE REVIEW

**Comment by weiznich** [comment]
@diesel-rs/core  I propose to do a final stable diesel 2.0 release next week. Please leave a comment here if you have any objections. I will fill a PR against the web repository next week so that we also update the webpage to diesel 2.0 + include the migration guide, the changelog and a small release post there.

**Comment by Ten0** [comment]
> I propose to do a final stable diesel 2.0 release next week. Please leave a comment here if you have any objections.

The two things I have in mind that slightly scare me with regards to backwards compatibility upon solving are the following two comments:
1. https://github.com/diesel-rs/diesel/issues/1612#issuecomment-1096987553
2. https://github.com/diesel-rs/diesel/pull/2799#pullrequestreview-708943633
    I'm not super confident with the current approach of https://github.com/diesel-rs/diesel/pull/2799#issuecomment-903161724 because that introduces:
    
     **a.** Unnecessary lifetime bounds on the deserialization part
     **b.** A somewhat-global config at the connection level, whereas whether you want to use one or the other would more typically depend on the amount of data you're querying and what you're doing with it afterwards (unless row-by-row is always ~faster) - which appears to be fundamentally more fine-grained than connection-level. 
     
   If however row-by-row is always ~faster, having just that version is always ideal and consistent across all backends so we could probably keep just that.

Unfortunately I have been very busy with other topics and couldn't work on these yet.

 - I've commented at 1. on this topic.
 - Would you agree it would be useful to have the benchmark suggested in 2's comment and the decision would depend on it?
 - If so, what do you think would be a reasonable timing to attempt implementation?

**Comment by weiznich** [comment]
> Return a iterator from Connection::load #2799 (review)
> I'm not super confident with the current approach of
> 
> Return a iterator from Connection::load #2799 (comment) because that introduces:
> 
> a. Unnecessary lifetime bounds on the deserialization part
> b. A somewhat-global config at the connection level, whereas whether you want to use one or the other would more typically depend on the amount of data you're querying and what you're doing with it afterwards (unless row-by-row is always ~faster) - which appears to be fundamentally more fine-grained than connection-level.
> 
> If however row-by-row is always ~faster, having just that version is always ideal and consistent across all backends so we could probably keep just that.

I remember that I've done some experimentation back then but I cannot find the corresponding code anymore. Will try to have another look in the next days. 
What I remember is that the row by row mode was significantly slower for all of our benchmarks. I think the main issue there was that it allocates things per row again and again, where the "normal" mode reuses buffers and other things.

To address the concrete points:

> a. Unnecessary lifetime bounds on the deserialization part

Yes the lifetime for `Cursor` is not optimal right now, but `Cursor` is not part of the public API. That means we can remove the lifetime if it turns out that we do not need it. That wouldn't work the other way around.

> b. A somewhat-global config at the connection level, whereas whether you want to use one or the other would more typically depend on the amount of data you're querying and what you're doing with it afterwards (unless row-by-row is always ~faster) - which appears to be fundamentally more fine-grained than connection-level.

The point is there is not really an other place to configure this than the connection, because as soon as you call `load_iter()` or whatever the query is already executed. What we could do is to provide the connection level configuration with some documentation that basically says: Do not use this if you don't call `Connection::load` directly. Then we could modify `RunQueryDsl` to do "runtime type checking" to see if the connection is a `PgConnection` and just enable that mode there transparently. That would be hacky but would result in that behaviour most people would expect.

**Comment by Ten0** [comment]
> The point is there is not really an other place to configure this than the connection, because as soon as you call `load_iter()` or whatever the query is already executed

I was thinking about the design described in that comment : https://github.com/diesel-rs/diesel/pull/2799#pullrequestreview-708943633

**Comment by weiznich** [comment]
I've put up a WIP PR for row by row mode in #3213 so that we could quickly check the performance implication of enabling it generally. 
That written: I would really prefer not to have backend specific methods there, but instead a way to enable it only for specific queries. Maybe even by wrapping the corresponding query into an "option" struct that signals this should be loaded via row-by-row mode. The WIP-PR contains some parts to just enable the row by row mode only for `load_iter()`.

**Comment by weiznich** [comment]
Closed in favor of #3237

**Pull request closed without merging**
