### PR TITLE
Change links to https

### PR DESCRIPTION
**Pull request by Ppjet6**
More TLS love!

### CODE REVIEW

**Comment by Ppjet6** [comment]
So many READMEs, more commits coming!

**Comment by Ppjet6** [comment]
I haven't converted the link to [www.apache.org](https://www.apache.org) in LICENSE-APACHE, not sure what to do here. If it's fine I'll push one more.
For the rest I checked and they don't support yet.

**Comment by notryanb** [comment]
LGTM 👍

@Ppjet6 I think a redirect might be a good idea if we want to force TSL for some reason? I don't really know enough to make a sound decision, but I'm assuming this helps with SEO?
side note - is there a way to `301` http -> https for docs pages?

**Comment by killercup** [comment]
Sorry to leave this hanging so long!

**Pull request merged**
