### PR TITLE
Update dotenv to 0.9

### PR DESCRIPTION
**Pull request by Eijebong**
maybe It should be >= 0.8, < 0.10 ?

### CODE REVIEW

**Comment by killercup** [comment]
Yeah, if you can use `>= 0.8, < 0.10`, it will not be breaking change for our users :)

**Comment by Eijebong** [comment]
I'll change it tonight. What about examples ? Should I loosen those dependencies too?

**Comment by killercup** [comment]
No need to change the examples, just the library core crates.

**Comment by felipesere** [comment]
Nudge... Can this be merged? 😸

**Pull request merged**
