### PR TITLE
Rename extension traits according to rfc 445

### PR DESCRIPTION
**Pull request by toshokan**
as of rfc 445, the the Rust convention for extension traits is `Ext` suffix. This PR makes `OptionalExtension` conform to this convention.

### CODE REVIEW

**Comment by weiznich** [comment]
I'm not sure if that's enough reason to do such a breaking change, given that this will likely have a bigger impact.

**Comment by toshokan** [comment]
It could always be done next time there is a larger breaking change, but since the contribution guide recommends the Rust style guide I think it's reasonable to conform where possible. 

Since this is in `prelude` I can't imagine many users are depending on the name of the trait explicitly anyway.

**Comment by weiznich** [comment]
That's all fine, but this remains to be a breaking change. So we cannot simply change out of the blue. This needs a more extended motivation + a migration strategy and so on.
Given all that is a lot of work I'm not sure that is justified for this purely cosmetic change.

**Comment by sgrif** [comment]
Yeah I agree, this seems like needless breakage without a strong motivation

**Comment by weiznich** [comment]
Closed because it seems to be the consent of the core that this is needless breakage.

**Pull request closed without merging**
