### PR TITLE
Backport a set of fixes to 1.4.x

### PR DESCRIPTION
**Pull request by helaan**
As requested in #2148, backport some commits to fix the documentation error. As requested in that commit, the SQLite bump is also included, as are a set of commits to make Diesel compile without warning on 1.38.0

### CODE REVIEW

**Comment by weiznich** [comment]
I see now that libsqlite-sys 0.16 is released. Maybe we should bump that crate again to 0.16 before the release. Can you do add that to this PR?

**Comment by helaan** [comment]
I've bumped libsqlite3-sys in #2183, will backport that when that one is merged.

**Comment by weiznich** [comment]
I've just realized that this PR is not #2175 so I've just drop the list from there here :see_no_evil: 

#2019
#2056
#2108
#2102
#2164

I think #2019, #2056 and #2164 are missing. It would be great to also get them.

**Comment by helaan** [comment]
I've incorporated #2019 and #2056, however #2164 requires additional work, which I'm not sure are worth it at this point, as Diesel doesn't expose types from syn and users of syn-1.0 libraries can just pull in another version of syn.

**Comment by weiznich** [comment]
I've added #2164 to minimize duplicated syn versions (and therefore build time) in complexer projects.

**Pull request merged**
