### PR TITLE
Deserialize json that is not prefixed with `1`

### LINKED ISSUE #2388: Unsupported JSONB encoding version
### Versions

- **Rust:** rustc 1.43.0 (4fb7144ed 2020-04-20)
- **Diesel:** 1.4.4
- **Database:** Postgres
- **Operating System** Windows 10 (but it's unrelated)

### Feature Flags

- **diesel:** ["postgres", "r2d2", "uuidv07", "serde_json"]

## Problem Description

It's not possible to fetch entity with `jsonb` column from the database. I'd like to share more information but error doesn't include data on which it failed (e.g. what version of JSONB it faced). See steps for reproduce.

UPD.

I forked 1.4.x and added some additional logging so I've got

```
DeserializationError("Unsupported JSONB encoding version 123")
```

### What are you trying to accomplish?

Fetch entity with `jsonb` column from the database

### What is the expected output?

fetch entity with `jsonb` column from the database

### What is the actual output?

`DeserializationError("Unsupported JSONB encoding version")`

### Are you seeing any additional errors?

No

### Steps to reproduce

1. Install Postgres 12.0
1. Create a table with `uuid` PK and `jsonb` field.
1. Insert some test data
1. Create table and entity model:
	```rust
	use diesel::prelude::*;
	use uuid::Uuid;
	use serde::{Serialize, Deserialize};
	use serde_json::Value as JsonValue;
	use diesel::table;

	#[derive(Queryable, Serialize, Deserialize, Debug)]
	pub struct CompanySettings {
		pub CompanyId: Uuid,
		pub Preset: JsonValue,
	}

	table! {
		dbo.CompanySettingsView (CompanyId) {
			CompanyId -> Uuid,
			Preset -> Jsonb,
		}
	}
	```
1. Try to fetch some data
	```rust
	use schema::CompanySettingsView::dsl::*;

	CompanySettingsView.limit(100).load::<CompanySettings>(&connection)
	```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues. Related to #1788
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

### PR DESCRIPTION
**Pull request by Pzixel**
Fixes #2388

### CODE REVIEW

**Comment by weiznich** [comment]
Closed because I cannot reproduce the underlying issue.
I'm open to discuss a fix, when we've found the root cause for the problem as I do not want to include any ad-hoc parsing here.

**Comment by Mingun** [comment]
At least information about what version exactly is not supported will be useful, because without that it maybe is very hard even just to google solution

**Comment by Pzixel** [comment]
I've commented solution in linked issue, it was my mistake that I messed up `text` with `jsonb`

**Comment by Mingun** [comment]
I see. But your PR contained some useful piece that could be extracted from it, if some desire

**Comment by weiznich** [comment]
@Mingun There is only a version 1 here. Additionally at least for a foreseeable future there will be no other version. That said, if somebody is willing to invest time to improve that message, sure do it, but at least for me there are much more important issues to solve in diesel.

**Pull request closed without merging**
