### PR TITLE
Backport changes to 1.4.x

### PR DESCRIPTION
**Pull request by tosti007**
As said in #2205 a PR should be made with all the required changes along with the changes labeled "maybe backport", so here it is.

I back ported all commits I deemed right, but the tests don't seem to pass on locally due to unrelated build failures.

Hopefully this helps (as I would like to use uuid 0.8) with a release prior to the milestone!

### CODE REVIEW

**Comment by weiznich** [comment]
97505e0 needs to be removed. That commit does break the build.

**Comment by mikeyhew** [comment]
Can I suggest you add [#2159: Fix formatting error with embedded migrations](https://github.com/diesel-rs/diesel/pull/2159)? It's a bugfix that was merged in September. Commit hash is 78ad40db5162ee3ef7e1a622d23c31e046035447

**Comment by weiznich** [comment]
That seems to be a reasonable addition. :+1:

**Comment by tosti007** [comment]
@weiznich Oops you're right.
@mikeyhew Thank you for the suggestion!

**Comment by weiznich** [comment]
Possible other candidates:

* https://github.com/diesel-rs/diesel/pull/2299
* https://github.com/diesel-rs/diesel/pull/2292
* https://github.com/diesel-rs/diesel/pull/2265

Seems like I missed tagging those ones while merging PR's

**Comment by tosti007** [comment]
If I want to add #2299, then #2230 and #2179 should be added as well I believe. Is this right or am I missing more?

**Comment by weiznich** [comment]
As #2179 brings in a new feature I would say we do not backport any of those 3 PR's. Patch releases are entirely bugfix releases, so no new features there.

**Comment by tosti007** [comment]
Alright, then I believe no more candidates are left (with the exception of #2299, but that relies on the new features).

**Comment by weiznich** [comment]
I will wait a few more days if any other members of @diesel-rs/contributors have some opinion here and then I will try to do a release.

**Comment by weiznich** [comment]
Merged and released (with minor changes) as 1.4.4 :tada:

**Pull request merged**
