### PR TITLE
Update clippy to 0.0.126

### PR DESCRIPTION
**Pull request by DorianListens**
This change updates clippy, and updates the travis nightly version to
2017-04-25.

### CODE REVIEW

**Comment by killercup** [comment]
There are literally no feature changes in clippy between 0.0.125 and 0.0.126. Did anything cool land in nightly since April 19?

You can always `rustup overwrite add nightly-2017-04-19` in your diesel directory.

**Comment by DorianListens** [comment]
Sure, I could, but we'd need to make these changes eventually, wouldn't we? Is there a reason to lag behind nightly?

**Comment by killercup** [comment]
Laziness :) I'm fine with merging this as you already put the work in
basically but it's more fun to update clippy when there are new lints that
help us :)

Dorian Scheidt <notifications@github.com> schrieb am Mi. 26. Apr. 2017 um
18:36:

**Comment by sgrif** [comment]
In general I'd rather not chase the latest versions on these unless we have a specific reason to update, or there's been a Rust release.

**Comment by DorianListens** [comment]
Entirely reasonable. I was operating under the principle that "rustup update && bin/test" should "just work", but I'm happy to be a little less enthusiastic about nightly releases and instead pin myself to the version in .travis.yml.

**Comment by Eijebong** [comment]
Plus clippy is always behind nightly sometimes by two or three days.

**Comment by sgrif** [comment]
Either way this PR more or less coincided with a Rust release, so it's fine

**Pull request merged**
